### ISSUE TITLE
v4.0 TODO

### ISSUE THREAD

**Issue by KagamiChan** [poooi/plugin-map-hp#10]
map hp v4.0 is to be compatible with poi v7.3.0+
Tasks to complete:
- [x] improve display style
- [x] remove final HP reducer
- [ ] add final HP indicator to maps where available

As it is better to test with latest event map API, this version is to complete during next event

**Comment by KagamiChan** [comment]
all done
